runtime:
  cache_dir: ./.cache/antora

site:
  title: BUILD-A-CONTAINER WORKSHOP
  url: https://bfarr-rh.github.io/build-a-container/
  start_page: intro-container-workshop::index.adoc

content:
  edit_url: ~
  sources:
    - url: .
      tags: []
      branches: ["master", "optional-exercises"]
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
    # Experimental allows things like keyboard binding macros
    experimental: true
    extended-content: false
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js
ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.12/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
