---
- name: gather facts
  gather_facts:

- name: Gather package facts
  package_facts:
    manager: auto

- name: Gather service facts
  service_facts:

- name: Install AWS CLI client 
  dnf:
    name:
      - awscli

...
